# prevent dropping into pry when nothing is happening
interactor :off
notification :terminal_title

guard :rspec, all_on_start: true, cmd: 'bundle exec rescue rspec' do
  watch(%r{^spec/(.+)_spec\.rb$})
  watch(%r{^lib/(.+)\.rb$})           { |m| "spec/lib/#{m[1]}_spec.rb" }
  watch(%r{^spec/spec_helper.*\.rb$}) { 'spec' }
end
